### ISSUE TITLE
CSS functions in declarations not getting padded with a space

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#1031]
For example this
```css
h1, h2 {
  border-top: 3px solid var(--color-secondary);
}
```

Comes out as this, missing the space between the space, causing the styles to fail
```css
h1, h2 {
  border-top: 3px solidvar(--color-secondary);
}
```
