### ISSUE TITLE
functions in CSS declarations (like CSS `var`) are being incorrectly optimized

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#1242]
## Summary
When writing a CSS selector that has a CSS Variable (`Function`) that comes _after_ something like an `Identifier`, the resulting CSS is incorrectly optimized with a space missing between the `Declaration` values

**Input**
```css
.snippet {
  padding: 0 var(--size-4);
}
```

**Output**
```css
# actual
.snippet{padding:0var(--size-4);}

# expected
.snippet{padding:0 var(--size-4);}
```

and thus "breaks" in browsers
![Screenshot 2024-06-07 at 11 38 29 AM](https://github.com/ProjectEvergreen/greenwood/assets/895923/87a0aa7f-17d6-49ea-b727-cc3b524d4a87)

## Details
Interestingly enough, the other way around works just fine

**Input**
```css
.snippet {
  margin: var(--size-4) 0;
}
```

**Output**
```css
.snippet{margin:var(--size-4) 0;}
```
![Screenshot 2024-06-07 at 11 38 29 AM](https://github.com/ProjectEvergreen/greenwood/assets/895923/87f2ba7f-659a-4249-b030-1ef839ddc0a5)
