### ISSUE TITLE
CSS bundling optimization not handling transitive relative `url(...)` references

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#1346]
## Type of Change

Bug

## Summary

So there is an issue if you `@import` a CSS file and _that_ CSS file has references to other files via `url(...)`, the CSS bundling will not pick it up.  For example, give a dependency on **font-awesome**

```css
/* src/styles/main.css */
@import "../node_modules/font-awesome/css/font-awesome.css";
```

It has references to [its own font files](https://unpkg.com/browse/font-awesome@4.7.0/css/font-awesome.css)
```css
/* /node_modules/font-awesome/css/font-awesome.css */
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.7.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.7.0') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2?v=4.7.0') format('woff2'), url('../fonts/fontawesome-webfont.woff?v=4.7.0') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.7.0') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

However, in the browser we will get a 404 for these assets and of course none of the icons will show
![Screenshot 2024-12-14 at 9 26 21 AM](https://github.com/user-attachments/assets/53b3d642-0116-4773-a310-c31e88b157ad)

![Screenshot 2024-12-14 at 9 26 21 AM](https://github.com/user-attachments/assets/79876211-4ec8-41b0-9899-fc6cb611cc55)

> You can see the repo here - https://github.com/AnalogStudiosRI/www.analogstudios.net

## Details

Admittedly I was aware of this short coming for some time, hence why I had made a dedicated [third party plugin](https://github.com/AnalogStudiosRI/greenwood-plugin-font-awesome) for resolving and managing **font-awesome** related assets, but after the work coming out of https://github.com/ProjectEvergreen/greenwood/pull/1326 and https://github.com/ProjectEvergreen/greenwood/issues/1338 this is indeed a solvable problem, and now I can see it working here - https://github.com/AnalogStudiosRI/www.analogstudios.net/pull/101
