### ISSUE TITLE
bundling for CSS relative node_modules based `url` references breaks

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#1368]
## Type of Change

Bug

## Summary

Looks like "self managed" relative references to _node_modules_ will produce a 500 error in the console because it looks like an extra `/node_modules/{specifier}/` is being prepended to the link.
```css
@font-face {
  font-family: "Geist-Sans";
  src: url("../../node_modules/geist/dist/fonts/geist-sans/Geist-Regular.woff2") format("truetype");
}

@font-face {
  font-family: "Geist-Mono";
  src: url("../../node_modules/geist/dist/fonts/geist-mono/GeistMono-Regular.woff2")
    format("truetype");
}

@font-face {
  font-family: "Geist-Sans Bold";
  src: url("../../node_modules/geist/dist/fonts/geist-sans/Geist-Bold.woff2") format("truetype");
}
```

![Screenshot 2024-12-28 at 12 14 44 PM](https://github.com/user-attachments/assets/344a6edb-f7cf-4d00-88e5-6c184f92c8b0)
![Screenshot 2024-12-28 at 12 17 33 PM](https://github.com/user-attachments/assets/3a138bd7-5e21-4179-aa6a-e2790c165014)

## Details

Seems to be a regression / oversight from #1346 .  See this PR for reference - https://github.com/ProjectEvergreen/www.greenwoodjs.dev/pull/146
