### ISSUE TITLE
bundled static assets from node_modules not getting uploaded to Cloudflare

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#1431]
### What happened?

Noticed in https://github.com/thescientist13/www.owenascode.dev/issues/24 and confirmed by https://github.com/cloudflare/workers-sdk/issues/3615 that any files starting with _node_modules/_ in the public build directory are not getting uploaded, as in this case above, the bundled font files were missing in production deployments 

![Image](https://github.com/user-attachments/assets/59a6ab17-6d3a-4b18-b8cd-d955ac97efaf)

### Steps to reproduce

1. Link to a file in _node_modules_ from a CSS file added a `<link>` tag in a page
    ```css
    @font-face {
      font-family: "Ubuntu";
      src: url("../../node_modules/@fontsource/ubuntu/files/ubuntu-latin-500-normal.woff2")
        format("truetype");
    }
    ```
1. Deploy to Cloudflare Pages

### Environment

- Greenwood - v0.30.0
- Cloudflare pages

### Additional Context

A simple patch test shows that if we just rename the start of the file to _node-modules_ it will work - https://github.com/thescientist13/www.owenascode.dev/pull/25/files#diff-bf1bd480967a87e8817935ffb2315dc10544aadc91f01fac86207af3dcb29e2f

![Image](https://github.com/user-attachments/assets/b0395577-f392-406d-bb37-b9bb687c1909)

This might be a general consideration for other hosting platforms, so can't hurt to add this to the CLI since it's a simple enough fix.
