### ISSUE TITLE
broken custom-media queries

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/greenwood#363]
## Type of Change
- [ ] New Feature Request
- [x] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Currently, our site banner and page-template utilise the [evergreen web component library](https://github.com/hutchgrant/evergreen-web-components) which was previously using postcss-next.   With that deprecation, and with using postcss-preset-env instead, our `@custom-media` queries don't work correctly. With the updated component library, along with postcss-preset-env set to `stage: 1`,  we can utilize these components correctly responsively.  

## Details

Current `<eve-container></eve-container>` element is not breaking correctly on different size windows. That's because @custom-media wasn't being loaded properly by postcss.  We need to set postcss-preset-env to `stage: 1` in addition to updating the `@greeenwood/www package.json` with the new updated `@evergreen-wc/eve-container: ^0.0.10`

**Comment by thescientist13** [comment]
@hutchgrant 
Was reviewing the deploy preview of #366 but wasn't able to see the breakpoint issue you are referring to?  (essentially greenwoodjs.io/docs/configuration and  https://deploy-preview-366--elastic-blackwell-3aef44.netlify.app/docs/configuration).

Could you maybe post a screenshot in your issue description and detail / document what is broken, and so what could be verified to confirm it was fixed?

**Comment by hutchgrant** [comment]
`<eve-container></eve-container>` in banner has broken media query

![broken_media_query](https://user-images.githubusercontent.com/1429612/84599580-08aec480-ae41-11ea-97b3-4b493efdbc13.png)

**Comment by thescientist13** [comment]
So are you saying it should be broken down even further at lower break points?  

As I mentioned, comparing this against prod website it looked / behaved the same, so from a user perspective was anything fixed?  Not sure then what is "broken" here then, per se?

**Comment by hutchgrant** [comment]
Here's is the fixed @custom-media query from #366 

![fix_media_query](https://user-images.githubusercontent.com/1429612/84599635-73600000-ae41-11ea-9824-b576c217d774.png)

**Comment by hutchgrant** [comment]
@custom-media is basically like a css variable for media queries.

When those aren't being compiled correctly because in evergreen-wc it was compiled with postcss-cssnext which is deprecated.  So the component itself had to be updated and the postcss-preset-env stage 1 had to be used for the media query to function properly.

**Comment by hutchgrant** [comment]
css from the container (also navigation component uses similar @custom-media var).

```css
@custom-media --screen-xs (max-width: 576px);
@custom-media --screen-sm (min-width: 576px);
@custom-media --screen-md (min-width: 768px);
@custom-media --screen-lg (min-width: 992px);
@custom-media --screen-xl (min-width: 1200px);

:host {
  & .container {
    margin-right: auto;
    margin-left: auto;
    padding-left: 15px;
    padding-right: 15px;
  }

  & .container-fluid {
    margin-right: auto;
    margin-left: auto;
    padding-left: 15px;
    padding-right: 15px;
  }

  @media (--screen-xs) {
    & .container {
      width: calc(100% - 30px);
    }
  }
  @media (--screen-sm) {
    & .container {
      width: 540px;
    }
  }
  @media (--screen-md) {
    & .container {
      width: 720px;
    }
  }
  @media (--screen-lg) {
    & .container {
      width: 960px;
    }
  }
  @media (--screen-xl) {
    & .container {
      width: 1140px;
    }
  }
}
```
