### ISSUE TITLE
double quotes inside `import`ed CSS breaks

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#678]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
As observed in https://github.com/thescientist13/greenwood-starter-presentation/pull/18, if the CSS being used with `import` has double quotes around it (`"`) which is what Greenwood wraps CSS is with when transforming it to JS, the returned JS breaks in the console because of the `"`. 
```css
:root {
  .
  .
  .
  --backgroundUrl: url("/assets/background.jpg");
}
```

![image](https://user-images.githubusercontent.com/895923/127782129-aee34bb3-1b66-425d-bd89-a145d77766d3.png)

## Details
So whatever Greenwood wants to wrap in, it should just make sure [to escape it properly](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/plugin-import-css/src/index.js#L33) for userland.  Hopefully can be captured through a spec.

**Comment by thescientist13** [comment]
Found out while testing https://github.com/ContributaryCommunity/www.contributary.community/pull/94 that for some reason there was escaped quoted CSS in there already like
```css
&::after {
  content: \"\";
  position: absolute;
  right: 0.8em;
  top: 0.9em;
  border: 0.3em solid var(--drop-text-color);
  border-color: var(--drop-text-color) transparent transparent transparent;
  transition: 0.4s all ease-in-out;
}
```

which with our fix was causing a double escape and completely, and silently breaking everything and then the dropdown wasn't rendering.
<img width="1670" alt="Screen Shot 2021-08-07 at 9 57 56 PM" src="https://user-images.githubusercontent.com/895923/128618352-27a53ca5-cb13-4bd2-afca-11d7a2517df5.png">

I realized while debugging instead of trying to [escape all the quotes](https://github.com/ProjectEvergreen/greenwood/pull/679/files#diff-cf55974da62a4c009f65a2c24eced868bfbf3a29e9816cc9d88852125bca8e29R33) or worrying if they've been escaped for some reason already, a cleaner solution could just be to wrap our CSS-in-JS in template literals instead.
```js
const cssInJsBody = `const css = \`${body.replace(/\r?\n|\r/g, ' ')}\`;\nexport default css;`
```
