### ISSUE TITLE
assets (fonts) with query strings not loading correctly with production build (`greenwood serve`)

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#764]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
Noticed that when integrating **font-awesome** into [a project](https://github.com/AnalogStudiosRI/www.analogstudios.net/pull/17), it uses [query strings within its file reference to its font files from its CSS](https://unpkg.com/browse/font-awesome@4.6.3/css/font-awesome.css).
```css
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.6.3');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.6.3') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2?v=4.6.3') format('woff2'), url('../fonts/fontawesome-webfont.woff?v=4.6.3') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.6.3') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.6.3#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

This causes an issue with the prod server wherein this content (with a query string) is not loaded.  (Returns a `204`)
![Screen Shot 2021-10-12 at 11 32 33 AM](https://user-images.githubusercontent.com/895923/136987950-f526ae6d-7fc7-4aae-8cf7-1e5894548fad.png)

## Details
This seems similar to a previous bug #579 but looks like I may have missed [a case](https://github.com/ProjectEvergreen/greenwood/blob/v0.17.0-alpha.0/packages/cli/src/lifecycles/serve.js#L184) where i need to strip query params before handing off a URL for file resolution.
